/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupchatclient;

import java.io.IOException;
import static java.lang.System.exit;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.MulticastSocket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.SourceDataLine;
import javax.sound.sampled.TargetDataLine;

/**
 *
 * @author user
 */
public class StartGroupCall extends javax.swing.JFrame {
    public static int port_server = 9000;
    public static String add_server="192.168.0.21";
    public static int port_server_name =9051;
    public static int port_client_player = port_server+3;
    public static int port_notice = 9006;
    public static boolean no_mute =true;
    
    TargetDataLine audio_in;
    //TargetDataLine audio_in1;
    SourceDataLine audio_out;
    SourceDataLine audio_out1;
    
    public static AudioFormat getaudioformat(){
       float sampleRate=22050;
        int sampleSizeInBits=8;
        int channel=1;
        boolean signed=true;
        boolean bigEndian=false;
        return new AudioFormat(sampleRate, sampleSizeInBits, channel, signed, bigEndian);
    }
    /**
     * Creates new form StartGroupCall
     */
    public StartGroupCall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_start = new javax.swing.JButton();
        input_name = new javax.swing.JTextField();
        btn_name = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        set_notice = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btn_end = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        names_area = new javax.swing.JTextArea();
        btn_mute = new javax.swing.JButton();
        btn_enableAudio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        btn_name.setText("Set Name");
        btn_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nameActionPerformed(evt);
            }
        });

        set_notice.setColumns(20);
        set_notice.setRows(5);
        jScrollPane1.setViewportView(set_notice);

        jLabel1.setText("Notice");

        btn_end.setText("Log Out");
        btn_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_endActionPerformed(evt);
            }
        });

        names_area.setColumns(20);
        names_area.setRows(5);
        jScrollPane2.setViewportView(names_area);

        btn_mute.setText("Mute");
        btn_mute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_muteActionPerformed(evt);
            }
        });

        btn_enableAudio.setText("Enable Audio");
        btn_enableAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enableAudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_end, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_name, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_enableAudio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(btn_mute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_enableAudio)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_start)
                    .addComponent(btn_end))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        init_audio();
        receive_notice();
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nameActionPerformed
        try {
            // TODO add your handling code here:
            String name = input_name.getText();
            String sendString = name+" * ";
            InetAddress ip = InetAddress.getByName(StartGroupCall.add_server);
            DatagramPacket dp = new DatagramPacket(sendString.getBytes(), 0, sendString.length(), ip, StartGroupCall.port_server_name );
            GroupChatClient.socket_name.send(dp);
            System.out.println(dp.getAddress()+" "+ dp.getPort());
            ShowName n = new ShowName();
            n.start();
        } catch (IOException ex) {
            Logger.getLogger(StartGroupCall.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_nameActionPerformed

    private void btn_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_endActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String name = input_name.getText();
            String sendString = name+" no ";
            InetAddress ip = InetAddress.getByName(StartGroupCall.add_server);
            DatagramPacket dp = new DatagramPacket(sendString.getBytes(), 0, sendString.length(), ip, StartGroupCall.port_server_name );
            GroupChatClient.socket_name.send(dp);
            exit(0);
        } catch (IOException ex) {
            Logger.getLogger(StartGroupCall.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_endActionPerformed

    private void btn_muteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_muteActionPerformed
        // TODO add your handling code here:
        no_mute=false;
        
    }//GEN-LAST:event_btn_muteActionPerformed

    private void btn_enableAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enableAudioActionPerformed
        try {
            // TODO add your handling code here:
            no_mute=true;
            AudioFormat format2=getaudioformat();
            DataLine.Info info2=new DataLine.Info(TargetDataLine.class, format2);
            if(!AudioSystem.isLineSupported(info2)){
                System.out.println("not support");
                System.exit(0);
            }
            audio_in=(TargetDataLine) AudioSystem.getLine(info2);
            audio_in.open(format2);
            audio_in.start();
            Recorder_Thread r=new Recorder_Thread();
            InetAddress inetaddress = null;
            try {
                inetaddress = InetAddress.getByName(add_server);
            } catch (UnknownHostException ex) {
                Logger.getLogger(StartGroupCall.class.getName()).log(Level.SEVERE, null, ex);
            }
            r.audio_in=audio_in;
            r.server_ip=inetaddress;
            r.server_port=port_server;
            r.start();
            
        } catch (LineUnavailableException ex) {
            Logger.getLogger(StartGroupCall.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_enableAudioActionPerformed
public void init_audio(){
   
        try {
            AudioFormat format=getaudioformat();
            DataLine.Info info=new DataLine.Info(TargetDataLine.class, format);
            if(!AudioSystem.isLineSupported(info)){
                System.out.println("not support");
                System.exit(0);
            }
            audio_in=(TargetDataLine) AudioSystem.getLine(info);
            audio_in.open(format);
            audio_in.start();
            System.out.println(audio_in.getLevel());
            Recorder_Thread r=new Recorder_Thread();
            InetAddress inet=InetAddress.getByName(add_server);
            r.audio_in=audio_in;
            r.server_ip=inet;
            r.server_port=port_server;
            GroupChatClient. calling = true;
            r.start();
            
            AudioFormat format_out=getaudioformat();
            DataLine.Info info_out=new DataLine.Info(SourceDataLine.class, format_out);
            if(!AudioSystem.isLineSupported(info_out)){
                System.out.println("not support");
                System.exit(0);
            }
            audio_out=(SourceDataLine)AudioSystem.getLine(info_out);
            audio_out.open(format_out);
            audio_out.start();
            Player_Thread p =new Player_Thread(); 
            p.audio_out = audio_out;
            GroupChatClient.calling = true;
            p.start();
            
            AudioFormat format_out1=getaudioformat();
            DataLine.Info info_out1=new DataLine.Info(SourceDataLine.class, format_out1);
            if(!AudioSystem.isLineSupported(info_out1)){
                System.out.println("not support");
                System.exit(0);
            }
            audio_out1=(SourceDataLine)AudioSystem.getLine(info_out1);
            audio_out1.open(format_out1);
            audio_out1.start();
            Player_Thread1 p1 =new Player_Thread1(); 
            p1.audio_out1 = audio_out1;
            GroupChatClient.calling = true;
            p1.start();
            
            btn_start.setEnabled(false);
        } catch (LineUnavailableException | UnknownHostException  ex) {
            Logger.getLogger(StartGroupCall.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void receive_notice(){
   ReceiveNotice_Thread n =new ReceiveNotice_Thread();
   n.start();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGroupCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGroupCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGroupCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGroupCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGroupCall().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enableAudio;
    private javax.swing.JButton btn_end;
    private javax.swing.JButton btn_mute;
    private javax.swing.JButton btn_name;
    private javax.swing.JButton btn_start;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField input_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea names_area;
    public static javax.swing.JTextArea set_notice;
    // End of variables declaration//GEN-END:variables
}
